name: lint test
description: Action to perform lint test
runs:
  steps:
    - name: Install ESLint
      shell: bash
      run: npm install eslint
    - name: Run ESLint
      shell: bash
      run: npm run lint
