name: Deploy image to server
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Enter the tag
        type: string
        required: true
      environment:
        description: Select environment 
        type: choice
        options:
        - prod
        - uat
        - dev
        required: true
    
    
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: docker login --username pavanasalvankar --password Pavana123
  pull-docker-image:
    needs: docker-login
    runs-on: ubuntu-latest
    steps:
      - run: docker pull pavanasalvankar/weather:${github.events.inputs.tag}
  deploy-to-server:
    needs: pull-docker-image
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deployed successfully'
      
