name: docker build and push
on:
  pull_request:
    branches: [master]
jobs:
  steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5.8
      name: Build & push Docker image
      with:
        image: pavanasalvankar/weather
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

