name: build-and-push-docker-image
# Action to build and push the docker image to JFROG

on: 
  workflow_call:
  
jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set Docker Image Tag as Output
        id: SetDockerTag
        run: |
          echo "DockerTag=Pav" >> $GITHUB_OUTPUT
