name: build-and-push-docker-image
# Action to build and push the docker image to JFROG

on: 
  workflow_call:
    outputs:
      DockerTag:
        description: "Docker Image Tag"
        value: ${{ jobs.build-docker.outputs.DockerTag }}
jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      DockerTag: ${{ steps.SetDockerTag.outputs.DockerTag }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Docker Image Tag as Output
        id: SetDockerTag
        run: |
          echo "DockerTag=Pav" >> $GITHUB_OUTPUT
