name: lint and build test
on:
  pull_request:
    branches: [develop]

jobs:
  lint1:
    runs-on: ubuntu-latest
    steps:
      - name: lint using action
        uses: ./.github/actions/lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ESLint
        run: npm install eslint
      - name: Run ESLint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install react-scripts
        run: npm install react-scripts

      - name: build-ability
        run: npm run build
