name: pull-request-dev
on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set-output
        id: out
        run: echo arn=abc >> $GITHUB_OUTPUT
      - name: Print
        run: echo ${{ steps.out.outputs.arn }}
      - name: lint 
        uses: ./.github/actions/lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/build
