name: create-release
on:
  create:
    branches: [release/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/build

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.github_token}}      
      - uses: mr-smithers-excellent/docker-build-push@v5.8
        name: Build & push Docker image
        with:
          image: pavanasalvankar/weather
          tags: 1.0.1-uat-${{ steps.buildnumber.outputs.build_number }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  docker-image-deployment:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name : Depploy to UAT   
        run : echo 'Deployed to url https://uat.weather.com'
