name: pull-request-dev
on:
  pull_request:
    branches: [develop]
env:
  NAME: "Pavana"
  SURNAME: "Salvankar"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set-output
        id: out
        run: echo fullname=$(node --version)_${env.NAME}_${env.SALVANKAR} >> $GITHUB_OUTPUT
      - name: Print
        run: echo ${{ steps.out.outputs.arn }}
      - name: lint 
        uses: ./.github/actions/lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/build
