name: pull-request-master
on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint 
        uses: ./.github/actions/lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/build

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.github_token}}      
      - uses: mr-smithers-excellent/docker-build-push@v5.8
        name: Build & push Docker image
        with:
          image: pavanasalvankar/weather
          tags: dev, dev-latest, ${{ steps.buildnumber.outputs.build_number }}-dev
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  docker-image-deployment:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: mshick/add-pr-comment@v2
        with:
          message: 'Deployed to url https://dev.weather.com'
