name: After greetngs
on:
  workflow_run:
    workflows: [Greetings]
    types:
      - completed

jobs:
  run-automation-tests:
    name: Run automation blaze tests
    runs-on: ubuntu-latest
    steps:
      - name: Print URL
        run: echo "Greetings printed...."